name: Compile LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache TeX Live
      uses: actions/cache@v3
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-texlive-

    - name: Install TeX Live if not cached
      run: sudo apt-get install -y texlive-full
      if: steps.cache.outputs.cache-hit != 'true'  # Solo instalar si no se encuentra en caché

    - name: Compile LaTeX document
      run: |
        pdflatex document.tex

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: document.pdf
